---
--- Generated by Luanalysis
--- Created by admin.
--- DateTime: 2022/12/23 14:59
---
--比较线程标识与锁中的标识是否一致
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    --释放锁
    redis.call('del',KEYS[1])
end
return 0